[package]
name = "fat-fuse"
version = "0.1.0"
edition = "2021"

[dependencies]
fat = { path = "../os/fat" }
block-dev = { path = "../os/block-dev" }
send_wrapper = "0.6"
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
typed-bytesize = "0.1"
