[package]
name = "easy-fs"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
enumflags2 = { workspace = true }
log = { workspace = true }
spin = { workspace = true, features = ["mutex", "spin_mutex"] }
block-dev = { workspace = true }
