[package]
name = "easy-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
enumflags2 = "0.7.7"

[dependencies.spin]
version = "0.9"
default_features = false
features = ["mutex", "spin_mutex"]
