[package]
name = "user"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
buddy_system_allocator = "0.9.0"
enumflags2 = "0.7.7"
riscv = "0.10.1"
easy-fs = { path = "../easy-fs" }
